# Dependencies

highlighter:      pygments

# Permalinks
permalink:        pretty

title:            Chenting's Collection
tagline:          'A Jekyll theme'
email:            github.padded422@passmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A portfolio of personal QA automation projects demonstrating skills in test framework usage.
baseurl:          "/" 
url:              "https://cloffwang.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

author:
  name:           'Chenting Wang'
  url:            

paginate:         5
paginate_path:    "/_post/page:num"

# Custom vars
version:          0.9

github:
  repo:           https://github.com/poole/hyde



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
